class English {
  static const Map<String, String> message = {
    'home': 'Home',
    'skill' : 'Skill',
    'progress' : 'Progress',
    'account' : 'Account',
    'vocabulary' : 'Vocabulary',
    'homepage_greetings': 'Hi',
    'continue': 'Continue',
    'lesson': 'lesson',
    'home_question' : 'what will you study today ?',
    'words_start_learning' : "Let's start study !",
    'introducing_chatbot' : 'Chat with Chatbot',
    'learned_today' : 'Learned today',
    'continue_study' : 'Continue study',
    'title_flashcard_homepage' : 'Study vocabulary with FlashCard',
    'suggestion_flashcard_homepage' : '20 new words everyday',
    'daily_challenge': 'Daily Challenge',
    'start_now': 'Start Now',
    'choose_topic': 'Choose topic',
    'no_data': 'No data',
    'language': 'Language',
    'english': 'English',
    'vietnamese': 'Vietnamese',
    'welcome_back': 'Welcome back',
    'dark_mode': 'Dark mode',
    'logout': 'Logout',
    'saved_word': 'Saved word',
    'enter_message': 'Enter message...',
    'select_level': 'Select level',
    'no_level': 'No level',
    'for_beginner': 'For Beginner',
    'for_intermediate': 'For Intermediate',
    'for_advanced': 'For Advanced',
    'no_topic': 'No topic found',
    'list_saved_word': 'List saved words',
    'personal_profile': ' Personal profile',
    'name': 'Full Name',
    'age': 'Age',
    'job': 'Job',
    'avatar_url': 'Avatar url',
    'save_change': 'Save changes',
    'sex': 'Sex',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'edit_profile': 'Edit profile',
    'logout_successfully': 'Log out successfully',
    'user': 'User',
    'error': 'Error',
    'success': 'Success',
    'photo_uploaded': 'Photo uploaded',
    'photo_upload_failed': 'Photo upload failed',
    'profile_update_successful': 'Profile update successful',
    'cannot_save': 'Cannot save',
    'loading': 'Đang tải',
    'change_photo': 'Change photo',
    'congratulation': 'Congratulation!',
    'reviewed_all_card': 'You have reviewed all the cards.',
    'back_to_first': 'Back to the first card.',
    'submit': 'Submit',
    'play_audio': 'Play audio',
    'result': 'Result',
    'list_questions_answers': 'List of questions and correct answers',
    'sentence': 'Sentence',
    'correct_answer': 'Correct answer',
    'back_to_home_page': 'Back to home page',
    'practice_other_skills': 'Practice other skills',
    'check': 'Check',
    'name_required': 'Please enter your name',
    'name_invalid': 'Name cannot contain numbers or special characters',
    'age_required': 'Please enter your age',
    'age_must_be_number': 'Age must be a number',
    'age_must_be_positive': 'Age must be greater than 0',
    'age_must_be_less_than_100': 'Age must be less than 100',
    'occupation_required': 'Please enter your occupation',
    'occupation_invalid': 'Occupation cannot contain numbers or special characters',
    'please_check_input': 'Please check your information',
    'change_password': 'Change Password',
    'old_password': 'Old Password',
    'new_password': 'New Password',
    'confirm_new_password': 'Confirm New Password',
    'enter_old_password': 'Enter old password',
    'enter_new_password': 'Enter new password',
    'enter_confirm_password': 'Re-enter new password',
    'old_password_required': 'Please enter old password',
    'new_password_required': 'Please enter new password',
    'confirm_password_required': 'Please confirm new password',
    'passwords_not_match': 'Passwords do not match',
    'password_changed_successfully': 'Password changed successfully!',
    'password_change_failed': 'Failed to change password',
    'old_password_incorrect': 'Old password is incorrect',
  };
}
