class English {
  static const Map<String, String> message = {
    'home': 'Home',
    'skill' : 'Skill',
    'progress' : 'Progress',
    'account' : 'Account',
    'vocabulary' : 'Vocabulary',
    'homepage_greetings': 'Hi',
    'continue': 'Continue',
    'lesson': 'lesson',
    'home_question' : 'what will you study today ?',
    'words_start_learning' : "Let's start study !",
    'introducing_chatbot' : 'Chat with Chatbot',
    'learned_today' : 'Learned today',
    'continue_study' : 'Continue study',
    'title_flashcard_homepage' : 'Study vocabulary with FlashCard',
    'suggestion_flashcard_homepage' : '20 new words everyday',
    'daily_challenge': 'Daily Challenge',
    'start_now': 'Start Now',
    'choose_topic': 'Choose topic',
    'no_data': 'No data',
    'language': 'Language',
    'english': 'English',
    'vietnamese': 'Vietnamese',
    'welcome_back': 'Welcome back',
    'dark_mode': 'Dark mode',
    'logout': 'Logout',
    'saved_word': 'Saved word',
    'enter_message': 'Enter message...',
    'select_level': 'Select level',
    'no_level': 'No level',
    'for_beginner': 'For Beginner',
    'for_intermediate': 'For Intermediate',
    'for_advanced': 'For Advanced',
    'no_topic': 'No topic found',
    'list_saved_word': 'List saved words',
    'personal_profile': ' Personal profile',
    'name': 'Full Name',
    'age': 'Age',
    'job': 'Job',
    'avatar_url': 'Avatar url',
    'save_change': 'Save changes',
    'sex': 'Sex',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'edit_profile': 'Edit profile',
    'logout_successfully': 'Log out successfully',
    'user': 'User',
    'error': 'Error',
    'success': 'Success',
    'photo_uploaded': 'Photo uploaded',
    'photo_upload_failed': 'Photo upload failed',
    'profile_update_successful': 'Profile update successful',
    'cannot_save': 'Cannot save',
    'loading': 'Đang tải',
    'change_photo': 'Change photo',
  };
}
