class Vietnamese {
  static const Map<String, String> message = {
    'animal' : 'Con vật',
    'home': 'Trang chủ',
    'skill' : 'Kỹ năng',
    'progress' : 'Tiến độ',
    'account' : 'Tài khoản',
    'vocabulary' : 'Từ vựng',
    'homepage_greetings': 'Xin chào',
    'continue': 'Tiếp tục',
    'lesson': 'Bài',
    'home_question' : 'Bạn sẽ học gì hôm nay ?',
    'words_start_learning' : 'Hãy bắt đầu học nhé!',
    'introducing_chatbot' : 'Trò chuyện cùng Chatbot',
    'learned_today' : 'Hôm nay đã học',
    'continue_study' : 'Tiếp tục học',
    'title_flashcard_homepage' : 'Học từ vựng với thẻ ghi nhớ',
    'suggestion_flashcard_homepage' : '20 từ mới mỗi ngày',
    'daily_challenge': 'Thử thách mỗi ngày',
    'start_now': 'Bắt đầu ngay',
    'choose_topic': 'Chọn chủ đề',
    'no_data': 'Không có dữ liệu',
    'language': 'Ngôn ngữ',
    'english': 'Tiếng Anh',
    'vietnamese': 'Tiếng Việt',
    'welcome_back': 'Chào mừng trở lại',
    'dark_mode': 'Chế độ tối',
    'logout': 'Đăng xuất',
    'saved_word': 'Từ đã lưu',
    'enter_message': 'Nhập tin nhắn...',
  };
}
