class Vietnamese {
  static const Map<String, String> message = {
    'animal' : 'Con vật',
    'home': 'Trang chủ',
    'skill' : 'Kỹ năng',
    'progress' : 'Tiến độ',
    'account' : 'Tài khoản',
    'vocabulary' : 'Từ vựng',
    'homepage_greetings': 'Xin chào',
    'continue': 'Tiếp tục',
    'lesson': 'Bài',
    'home_question' : 'Bạn sẽ học gì hôm nay ?',
    'words_start_learning' : 'Hãy bắt đầu học nhé!',
    'introducing_chatbot' : 'Trò chuyện cùng Chatbot',
    'learned_today' : 'Hôm nay đã học',
    'continue_study' : 'Tiếp tục học',
    'title_flashcard_homepage' : 'Học từ vựng với thẻ ghi nhớ',
    'suggestion_flashcard_homepage' : '20 từ mới mỗi ngày',
    'daily_challenge': 'Thử thách mỗi ngày',
    'start_now': 'Bắt đầu ngay',
    'choose_topic': 'Chọn chủ đề',
    'no_data': 'Không có dữ liệu',
    'language': 'Ngôn ngữ',
    'english': 'Tiếng Anh',
    'vietnamese': 'Tiếng Việt',
    'welcome_back': 'Chào mừng trở lại',
    'dark_mode': 'Chế độ tối',
    'logout': 'Đăng xuất',
    'saved_word': 'Từ đã lưu',
    'enter_message': 'Nhập tin nhắn...',
    'select_level': 'Chọn cấp độ',
    'no_level': 'Không có cấp độ nào',
    'for_beginner': 'Cấp độ cơ bản',
    'for_intermediate': 'Cấp độ trung cấp',
    'for_advanced': 'Cấp độ nâng cao',
    'no_topic': 'Không tìm thấy chủ đề nào',
    'list_saved_word': 'Danh sách từ đã lưu',
    'personal_profile': 'Hồ sơ cá nhân',
    'name': 'Họ và tên',
    'age': 'Tuổi',
    'job': 'Nghề nghiệp',
    'avatar_url': 'Đường dẫn Ảnh đại diện ',
    'save_change': 'Lưu thay đổi',
    'sex': 'Giới tính',
    'male': 'Nam',
    'female': 'Nữ',
    'other': 'Khác',
    'edit_profile': 'Chỉnh sửa hồ sơ',
    'user': 'Người dùng',
    'error': 'Lỗi',
    'success': 'Thành công',
    'photo_uploaded': 'Đã tải ảnh lên',
    'photo_upload_failed': 'Tải ảnh lên thất bại',
    'profile_update_successful': 'Cập nhật hồ sơ thành công',
    'cannot_save': 'Không thể lưu thông tin',
    'loading': 'Loading',
    'change_photo': 'Đổi ảnh',
    'congratulation': 'Chúc mừng!',
    'reviewed_all_card': 'Bạn đã ôn tập tất cả các thẻ.',
    'back_to_first': 'Quay lại thẻ đầu tiên.',
    'submit': 'Nộp bài',
    'play_audio': 'Phát audio',
    'result': 'Kết quả',
    'list_questions_answers': 'Danh sách câu hỏi và đáp án đúng',
    'sentence': 'Câu',
    'correct_answer': 'Đáp án đúng',
    'back_to_home_page': 'Về trang chủ',
    'practice_other_skills': 'Luyện tập kỹ năng khác',
    'check': 'Kiểm tra',
    'name_required': 'Vui lòng nhập họ tên',
    'name_invalid': 'Họ tên không được chứa số hoặc ký tự đặc biệt',
    'age_required': 'Vui lòng nhập tuổi',
    'age_must_be_number': 'Tuổi phải là số',
    'age_must_be_positive': 'Tuổi phải lớn hơn 0',
    'age_must_be_less_than_100': 'Tuổi phải nhỏ hơn 100',
    'occupation_required': 'Vui lòng nhập nghề nghiệp',
    'occupation_invalid': 'Nghề nghiệp không được chứa số hoặc ký tự đặc biệt',
    'please_check_input': 'Vui lòng kiểm tra lại thông tin',
  };
}
