class Vietnamese {
  static const Map<String, String> message = {
    'animal' : 'Con vật',
    'home': 'Trang chủ',
    'skill' : 'Kỹ năng',
    'progress' : 'Tiến độ',
    'account' : 'Tài khoản',
    'vocabulary' : 'Từ vựng',
    'homepage_greetings': 'Xin chào',
    'continue': 'Tiếp tục',
    'lesson': 'Bài',
    'home_question' : 'Bạn sẽ học gì hôm nay ?',
    'words_start_learning' : 'Hãy bắt đầu học nhé!',
    'introducing_chatbot' : 'Trò chuyện cùng Chatbot',
    'learned_this_week' : 'Tuần này đã học',
    'continue_study' : 'Tiếp tục học',
    'title_flashcard_homepage' : 'Học từ vựng với thẻ ghi nhớ',
    'suggestion_flashcard_homepage' : '20 từ mới mỗi ngày',
    'test': 'Thi thử',
    'start_now': 'Bắt đầu ngay',
    'choose_topic': 'Chọn chủ đề',
    'no_data': 'Không có dữ liệu',
    'language': 'Ngôn ngữ',
    'english': 'Tiếng Anh',
    'vietnamese': 'Tiếng Việt',
    'welcome_back': 'Chào mừng trở lại',
    'dark_mode': 'Chế độ tối',
    'logout': 'Đăng xuất',
    'saved_word': 'Từ đã lưu',
    'enter_message': 'Nhập tin nhắn...',
    'select_level': 'Chọn cấp độ',
    'no_level': 'Không có cấp độ nào',
    'for_beginner': 'Cấp độ cơ bản',
    'for_intermediate': 'Cấp độ trung cấp',
    'for_advanced': 'Cấp độ nâng cao',
    'no_topic': 'Không tìm thấy chủ đề nào',
    'list_saved_word': 'Danh sách từ đã lưu',
    'personal_profile': 'Hồ sơ cá nhân',
    'name': 'Họ và tên',
    'age': 'Tuổi',
    'job': 'Nghề nghiệp',
    'avatar_url': 'Đường dẫn Ảnh đại diện ',
    'save_change': 'Lưu thay đổi',
    'sex': 'Giới tính',
    'male': 'Nam',
    'female': 'Nữ',
    'other': 'Khác',
    'edit_profile': 'Chỉnh sửa hồ sơ',
    'logout_successfully': 'Đăng xuất thành công!',
    'user': 'Người dùng',
    'error': 'Lỗi',
    'success': 'Thành công',
    'photo_uploaded': 'Đã tải ảnh lên',
    'photo_upload_failed': 'Tải ảnh lên thất bại',
    'profile_update_successful': 'Cập nhật hồ sơ thành công',
    'cannot_save': 'Không thể lưu thông tin',
    'loading': 'Loading',
    'change_photo': 'Đổi ảnh',
    'congratulation': 'Chúc mừng!',
    'reviewed_all_card': 'Bạn đã ôn tập tất cả các thẻ.',
    'back_to_first': 'Quay lại thẻ đầu tiên.',
    'submit': 'Nộp bài',
    'play_audio': 'Phát audio',
    'result': 'Kết quả',
    'list_questions_answers': 'Danh sách câu hỏi và đáp án đúng',
    'sentence': 'Câu',
    'correct_answer': 'Đáp án đúng',
    'back_to_home_page': 'Về trang chủ',
    'practice_other_skills': 'Luyện tập kỹ năng khác',
    'check': 'Kiểm tra',
    'name_required': 'Vui lòng nhập họ tên',
    'name_invalid': 'Họ tên không được chứa số hoặc ký tự đặc biệt',
    'age_required': 'Vui lòng nhập tuổi',
    'age_must_be_number': 'Tuổi phải là số',
    'age_must_be_positive': 'Tuổi phải lớn hơn 0',
    'age_must_be_less_than_100': 'Tuổi phải nhỏ hơn 100',
    'occupation_required': 'Vui lòng nhập nghề nghiệp',
    'occupation_invalid': 'Nghề nghiệp không được chứa số hoặc ký tự đặc biệt',
    'please_check_input': 'Vui lòng kiểm tra lại thông tin',
    'change_password': 'Đổi mật khẩu',
    'old_password': 'Mật khẩu cũ',
    'new_password': 'Mật khẩu mới',
    'confirm_new_password': 'Xác nhận mật khẩu mới',
    'enter_old_password': 'Nhập mật khẩu cũ',
    'enter_new_password': 'Nhập mật khẩu mới',
    'enter_confirm_password': 'Nhập lại mật khẩu mới',
    'old_password_required': 'Vui lòng nhập mật khẩu cũ',
    'new_password_required': 'Vui lòng nhập mật khẩu mới',
    'confirm_password_required': 'Vui lòng xác nhận mật khẩu mới',
    'passwords_not_match': 'Mật khẩu xác nhận không khớp',
    'password_changed_successfully': 'Đổi mật khẩu thành công!',
    'password_change_failed': 'Đổi mật khẩu thất bại',
    'old_password_incorrect': 'Mật khẩu cũ không đúng',
    'no_progress': 'Chưa có dữ liệu tiến độ',
    'skills_overview': 'Tổng quan kỹ năng',
    'learning_progress': 'Tiến độ học tập',
    'attempts': 'Lượt học',
    'score': 'Điểm',
    'study_time': 'Phút học',
    'correct': 'Đúng',
    'wrong': 'Sai',
    'exactly': 'Chính xác',
    'understood': 'Đã hiểu',
    'suggestions_from_AI': 'Gợi ý lộ trình từ AI',
    'mock_test_history': 'Lịch sử thi thử',
    'collapse': 'Thu gọn',
    'see_more': 'Xem thêm',
    'AI_is_analyzing_your_progress': 'AI đang phân tích tiến độ của bạn...',
    'close': 'Đóng',
    'no_suggestions_yet': 'Chưa có gợi ý',
    'suggested_learning_path': 'Gợi ý lộ trình học',
    'min': 'phút',
    'time': 'Thời gian',
    'exam': 'Đề',
    'choose_exam': 'Chọn đề thi:',
    'choose_the_correct_answer': 'Chọn câu trả lời đúng:',
    'cancel': 'Hủy',
    'you_answered': 'Bạn đã trả lời',
    'are_you_sure_you_want_to_submit': 'Bạn có chắc muốn nộp bài?',
    'list_of_questions': 'Danh sách câu hỏi',
    'Complete_the_test': 'Hoàn thành bài thi!',
    'come_back': 'Quay lại',
    'percentage_30': 'Cố lên nhé! Bạn cần ôn luyện thêm nhiều hơn!',
    'percentage_60': 'Tốt! Bạn đã nắm được cơ bản. Tiếp tục phát huy!',
    'percentage_80': 'Rất tốt! Bạn đã làm bài khá chắc chắn!',
    'percentage': 'Xuất sắc! Bạn đã hoàn thành bài thi một cách tuyệt vời!',
    'percentage_writing': 'Xuất sắc! Bạn đã hoàn thành bài tập một cách tuyệt vời!',
    'theme_complete': 'Hoàn thành chủ đề!',
    'search_topic': 'Tìm kiếm chủ đề',
    'no_results_found': 'Không tìm thấy kết quả',
    'view': 'Xem',
    'hide': 'Ẩn',
    'no_mock_tests': 'Không có bài đã thi thử',
    'no_learning_progress': 'Không có tiến độ học tập',
    'feedback': 'Nhận xét:',
    'your_score': 'Điểm của bạn',
    'finish_topic': 'Kết thúc chủ đề',
    'next_question': 'Câu hỏi tiếp theo',
    'check_answer': 'Kiểm tra câu trả lời',
    'enter_your_answer': 'Nhập câu trả lời của bạn vào đây...',
    'your_answer': 'Câu trả lời của bạn:',
    'only_1_question': 'Chỉ có 1 câu hỏi trong chủ đề này.',
    'question': 'Câu hỏi',
    'no_question_available': 'Không có câu hỏi nào.',
    'audio_sample': 'Âm thanh mẫu',
    'playing': 'Đang phát...',
    'tap_to_play': 'Bấm để phát',
    'your_speaking_answer': 'Câu trả lời của bạn',
    'scoring': 'Đang chấm điểm...',
    'completed': 'Đã hoàn thành',
    'press_to_stop': 'Đang ghi âm... Nhấn để dừng',
    'click_on_the_microphone': 'Nhấn vào micro để bắt đầu ghi âm',
  };
}
